#!/usr/bin/env python
#-*- coding:utf-8 -*-

import sys
import socket

COMMON_DOMAINS = [
    'api',
    'callbacks',
    'apt',
    'rpm',
    'repo',
    'www',
    'www1',
    'www2',
    'www3',
    'www4',
    'www5',
    'www6',
    'www7',
    'www8',
    'www9',
    'ws',
    'beta',
    'web',
    'ftp',
    'irc',
    'pptp',
    'old',
    'deprecated',
    'new',
    'dns',
    'dev',
    'test',
    'test2',
    'stage',
    'staging',
    'admin',
    'auth',
    'database',
    'db',
    'master',
    'slave',
    'mysql',
    'mariadb',
    'mongodb',
    'postgres',
    'webmail',
    'pop',
    'smtp',
    'mail',
    'intranet',
    'vpn',
    'vps',
    'jump',
    'jumpbox',
    'tunnel',
    'demo',
    'temp',
    'backend',
    'cms',
    'crm',
    'support',
    'blog',
    'help',
    'stats',
    'statistics',
    'health',
    'status',
    'owncloud',
    'nextcloud',
    'redmine',
    'source',
    'git',
    'gitlab',
    'svn',
    'hg',
    'mercurial',
    'bitbucket',
    'wiki',
    'mediawiki',
    'office',
    'backup',
    'virtual',
    'docker',
    'k8s',
    'kubernetes',
    'visma',
    'logs',
    'media',
    'static',
    'images',
    'img',
    'imgs',
    'assets',
    'cache',
    'episerver',
    'epi',
    'monitor',
    'monitoring',
    'sip',
    'a','b','c','d','e','f','g','h','i','j',
    'k','l','m','n','o','p','q','r','s','t',
    'u','v','w','x','y','z',
    'www.m',
    'shop',
    "cart",
    'store',
    'buy',
    'app',
    'cpanel',
    'home',
    'forum',
    'cdn',
    'secure',
    'whm',
    'files',
    'filetransfer',
    'portal',
    'member',
    'members',
    'community',
    'subscriber',
    'subscribers',
    'payment',
    'payments',
    'mobile',
    'phpmyadmin',
    'cloud',
    'fake',
    'login',
    'account',
    'accounts',
    'people',
    'live',
    'apps',
    'jira',
    'internal',
    'secret',
    'feed',
    'go',
    'redirect',
    'partners',
    'labs',
    'en',
    'us',
    'fr',
    'se',
    'uk',
    'fi',
    'dk',
    'de',
    'no',
    'au',
    'be',
    'ru',
    'ch',
    'it',
    'nl',
    'com',
    'next',
    'one',
    'two',
    'three',
    'four',
    'five',
    'six',
    'seven',
    'eight',
    'nine',
    'ten',
    'open',
    'info',
    'developer',
    'enterprise',
    'console',
    'try',
    'discuss',
    'docs',
    'newsletter',
    'premium',
    'feedback',
    'updates',
    'update',
    'download',
    'downloads',
    'projects',
    'project',
    'survey',
    'my',
    'server',
    'controller',
    'stream',
    'id',
    'marketing',
    'tracking',
    'campaign',
    'investors',
    'investor',
    'signup',
    'transition',
    'link',
    'links',
    'group',
    'ups',
    'dhl',
    'fedex',
    'distribution',
    'observer',
    'shopify',
    'wordpress',
    'aws',
    'heroku',
    'google',
    'squarespace',
    'resources',
    'preview',
]

def getIP(domain):
    try:
        data = socket.gethostbyname_ex(domain)
        ipx = data[2]
        return ipx
    except:
        return []

def main():

    result = []

    if len(sys.argv) != 2:
        print("Requiers a domain as argument")
        return 0;

    for i in COMMON_DOMAINS:
        domain = i+"."+sys.argv[1]
        ips = getIP(domain)
        if len(ips) != 0:
            sys.stdout.write("%s:\n" % domain)
            for ip in ips:
                sys.stdout.write("\t\t\t%s\n" % ip)
            sys.stdout.write('\n\n')
        sys.stdout.flush()



if __name__ == '__main__':
    sys.exit(main())


